services:
  postgres:
    image: postgres:16.6-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: apptest
    ports:
      - 5000:3000
    volumes:
      - .:/app
    command: npm run start

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: local-network
    external: true
